### ISSUE TITLE
LoveIt-tailwindcss RTL not working

### ISSUE THREAD

**Issue by hilyas** [i99dev/i99dev#1]
I tried the rtl hugo theme but it's not working. It just comes up as ltr. Am I missing something?
https://github.com/i99dev/LoveIt-tailwindcss

**Comment by i99dev** [comment]
@hilyas 
its works
<img width="1409" alt="2022-11-20_18-11-47" src="https://user-images.githubusercontent.com/10709888/202906952-5c67891c-f358-42d6-be97-fe300960b4bb.png">

**Comment by hilyas** [comment]
> @hilyas its works <img alt="2022-11-20_18-11-47" width="1409" src="https://user-images.githubusercontent.com/10709888/202906952-5c67891c-f358-42d6-be97-fe300960b4bb.png">

I meant I am having trouble with the LTR feature, I followed the instructions, I don't know if there are switches that need to be turned on. 
Anyway thank you for the follow up.

**Comment by i99dev** [comment]
@hilyas regarding  LTR, it works when changing the language to English from language switch when the web is running or from `config.toml`
